title: Siju Eapen Chacko # your name (or website title) here
logo: "/images/Photo_Logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data analytics expert and Python programmer with over 11 years of experience. My passion lies in using my technical know-how to create impactful projects that drive efficiency and optimize business decisions.
  <br><br>
  I graduated with a Distinction in my Master’s Degree in Data Science from Liverpool John Moores University. Currently, I provide data solutions for the weight team at Recaro Aircraft Seating, where I have successfully led global initiatives and developed tools that significantly enhance productivity and cost-efficiency.
  <br><br>
  My GitHub hosts various projects showcasing my ability to innovate and implement user-friendly tools that solve real-world problems. I also enjoy volunteering as a data solutions consultant and exploring new technologies through personal projects.
  <br><br>
  <a href="https://www.linkedin.com/in/siju-eapen-chacko/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
