title: Siju Eapen Chacko # your name (or website title) here
logo: "/images/Photo_Logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data analytics expert and Python programmer with 11+ years of experience, passionate about creating impactful solutions that drive efficiency and optimize decisions.
  <br><br>
  I earned a Distinction in my Master's in Data Science from Liverpool John Moores University and currently provide data solutions for the weight team at Recaro Aircraft Seating. I've led global initiatives and developed tools that boost productivity and cost-efficiency.
  <br><br>
  My GitHub features projects demonstrating my ability to innovate and create user-friendly tools. I also volunteer as a data consultant and enjoy exploring new technologies through personal projects.
  <br><br>
  <a href="https://www.linkedin.com/in/siju-eapen-chacko/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
